services:
  - type: web
    name: earth-wallet-bot
    env: node
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: PORT
        value: 3000 